"""
GrowFlow — Database Declarative Base and Metadata.

Provides the canonical SQLAlchemy ORM base class used by all future model
definitions. Gate 03 does not create domain entity tables; this establishes
the shared declarative infrastructure that later gates will build upon.

Architecture ref: 6B § 60 — Engineering: migrations mandatory, foreign keys,
constraints, controlled deletion, retry/idempotency design.

UUID primary keys and UTC timestamps follow the frozen 6B principles:
- UUIDs everywhere (6B § 9, 60)
- UTC timestamps (6B § 51)
"""

from __future__ import annotations

from datetime import UTC, datetime
import uuid

from sqlalchemy import DateTime, String, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """
    GrowFlow canonical SQLAlchemy declarative base.

    All ORM models must inherit from this class to participate in the
    same MetaData context and be tracked by Alembic migrations.
    """


class TimestampMixin:
    """
    Mixin providing UTC created_at and updated_at columns.

    Applied to entities that require standard timestamp auditing
    as mandated by 6B § 51.

    The server_default and onupdate are set at the database level
    so Alembic migrations can generate them correctly.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class UUIDPrimaryKeyMixin:
    """
    Mixin providing a UUID primary key column.

    GrowFlow uses UUIDs for all entity primary keys (6B § 9).
    The default is generated by the Python layer so that the
    identity is known before the INSERT completes.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        String(36),
        primary_key=True,
        default=uuid.uuid4,
        nullable=False,
    )


def utcnow() -> datetime:
    """Return the current UTC datetime (timezone-aware)."""
    return datetime.now(UTC)
